### ISSUE TITLE
Markdown语法问题

### ISSUE THREAD

**Issue by James-Hao** [xzzai/halo-theme-xue#23]
大佬~还是markdown的问题，我在halo后台写的文章，语法使文字变红色是可实现的，但是发布后文章中没有相应变红，辛苦大佬帮忙看看，感谢！
1. Markdown为：
![image](https://user-images.githubusercontent.com/32088388/89056712-0bcd2800-d38f-11ea-994d-37ce7e856718.png)
2. Halo后台表现为：
![image](https://user-images.githubusercontent.com/32088388/89056764-1daecb00-d38f-11ea-88ba-f517cf6c7f7d.png)
3. 发布后主题中显示为：
![image](https://user-images.githubusercontent.com/32088388/89056803-30290480-d38f-11ea-8418-f692ea943e6e.png)

相应文章链接见： https://www.haoxi.info/archives/typora%E5%92%8Cblogmd

再次感谢大佬！🙆🏻‍♂️

**Comment by James-Hao** [comment]
大佬~今天又遇到一个公式问题😧 我在主题中已经打开设置mathjax了，但是编写的公式还是无法正常显示
1. Markdown为：
![image](https://user-images.githubusercontent.com/32088388/89104517-7ee8a400-d44c-11ea-90a1-7476b7b82669.png)
2.Halo后台显示为：
![image](https://user-images.githubusercontent.com/32088388/89104519-8b6cfc80-d44c-11ea-929e-6b9ef95930cf.png)
3. 发布后显示为：
![image](https://user-images.githubusercontent.com/32088388/89104573-d9820000-d44c-11ea-9f42-c13d094eb13b.png)

希望大佬可以帮助，再次感谢！🙆🏻‍♂️

**Comment by hshanx** [comment]
> https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的 
![image](https://user-images.githubusercontent.com/23736683/89145190-94f88080-d582-11ea-8276-35263c0ab234.png)

**Comment by hshanx** [comment]
> 大佬~今天又遇到一个公式问题😧 我在主题中已经打开设置mathjax了，但是编写的公式还是无法正常显示
> 
> 1. Markdown为：
>    ![image](https://user-images.githubusercontent.com/32088388/89104598-09310800-d44d-11ea-818c-e929de866385.png)
>    2.Halo后台显示为：
>    ![image](https://user-images.githubusercontent.com/32088388/89104519-8b6cfc80-d44c-11ea-929e-6b9ef95930cf.png)
> 2. 发布后显示为：
>    ![image](https://user-images.githubusercontent.com/32088388/89104573-d9820000-d44c-11ea-9f42-c13d094eb13b.png)
> 
> 希望大佬可以帮助，再次感谢！🙆🏻‍♂️

你来一个公式来看看

**Comment by James-Hao** [comment]
> > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> 
> 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> 
> ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)

请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝

**Comment by hshanx** [comment]
> > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > 
> > 
> > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> 
> 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝


你来个文本呀，图片的都复制不了

**Comment by James-Hao** [comment]
> > > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > > 
> > > 
> > > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> > 
> > 
> > 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝
> 
> 你来个文本呀，图片的都复制不了

好嘞~😬
字变红的例子：
`d = <font color=red>`opening a gap`</font> ; e = <font color=red>`extending a gap`</font>`

公式的例子：
$$
F(i,y) = max\begin{cases}
F(i-1,j+1) + s(x_i,y_j) \\\\
F(i-1,j)+d \\\\
F(i,j-1)+d
\end{cases}
$$

**Comment by hshanx** [comment]
> > > > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > > > 
> > > > 
> > > > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > > > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> > > 
> > > 
> > > 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝
> > 
> > 
> > 你来个文本呀，图片的都复制不了
> 
> 好嘞~😬
> 字变红的例子：
> `d = <font color=red>`opening a gap`</font> ; e = <font color=red>`extending a gap`</font>`
> 
> 公式的例子：
> `$$ F(i,y) = max\begin{cases} F(i-1,j+1) + s(x_i,y_j) \\\\ F(i-1,j)+d \\\\ F(i,j-1)+d \end{cases} $$`

关于字变红，你可以在管理后台自定义的地方加一个 ，我这边是不会改整体样式的哟。
![image](https://user-images.githubusercontent.com/23736683/89161176-d732b980-d5a4-11ea-8891-16f16224d43d.png)

```css
<style type="text/css">
code {    color: inherit !important;}
</style>
```

**Comment by James-Hao** [comment]
> > > > > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > > > > 
> > > > > 
> > > > > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > > > > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> > > > 
> > > > 
> > > > 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝
> > > 
> > > 
> > > 你来个文本呀，图片的都复制不了
> > 
> > 
> > 好嘞~😬
> > 字变红的例子：
> > `d = <font color=red>`opening a gap`</font> ; e = <font color=red>`extending a gap`</font>`
> > 公式的例子：
> > `$$ F(i,y) = max\begin{cases} F(i-1,j+1) + s(x_i,y_j) \\\\ F(i-1,j)+d \\\\ F(i,j-1)+d \end{cases} $$`
> 
> 关于字变红，你可以在管理后台自定义的地方加一个 ，我这边是不会改整体样式的哟。
> ![image](https://user-images.githubusercontent.com/23736683/89161176-d732b980-d5a4-11ea-8891-16f16224d43d.png)
> 
> ```css
> <style type="text/css">
> code {    color: inherit !important;}
> </style>
> ```

好的~感谢大佬 我去添加尝试一下，另外大佬我可以把typora的vue主题的css文件如何改改应用到主题上吗？发给您一个vue的css文件，另外公式那个我查了查也不知道怎么解决😭 感谢！
[vue.css.zip](https://github.com/hshanx/halo-theme-xue/files/5014715/vue.css.zip)

**Comment by hshanx** [comment]
> > > > > > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > > > > > 
> > > > > > 
> > > > > > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > > > > > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> > > > > 
> > > > > 
> > > > > 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝
> > > > 
> > > > 
> > > > 你来个文本呀，图片的都复制不了
> > > 
> > > 
> > > 好嘞~😬
> > > 字变红的例子：
> > > `d = <font color=red>`opening a gap`</font> ; e = <font color=red>`extending a gap`</font>`
> > > 公式的例子：
> > > `$$ F(i,y) = max\begin{cases} F(i-1,j+1) + s(x_i,y_j) \\\\ F(i-1,j)+d \\\\ F(i,j-1)+d \end{cases} $$`
> > 
> > 
> > 关于字变红，你可以在管理后台自定义的地方加一个 ，我这边是不会改整体样式的哟。
> > ![image](https://user-images.githubusercontent.com/23736683/89161176-d732b980-d5a4-11ea-8891-16f16224d43d.png)
> > ```css
> > <style type="text/css">
> > code {    color: inherit !important;}
> > </style>
> > ```
> 
> 好的~感谢大佬 我去添加尝试一下，另外大佬我可以把typora的vue主题的css文件如何改改应用到主题上吗？发给您一个vue的css文件，另外公式那个我查了查也不知道怎么解决😭 感谢！
> [vue.css.zip](https://github.com/hshanx/halo-theme-xue/files/5014715/vue.css.zip)


这个vue主题，如果要完整引入的话，需要引入字体，对已这个来说，就有点大了。如果你要弄，我可以给你说怎么自定义，但是我计划作为主题的新功能了

**Comment by James-Hao** [comment]
> > > > > > > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > > > > > > 
> > > > > > > 
> > > > > > > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > > > > > > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> > > > > > 
> > > > > > 
> > > > > > 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝
> > > > > 
> > > > > 
> > > > > 你来个文本呀，图片的都复制不了
> > > > 
> > > > 
> > > > 好嘞~😬
> > > > 字变红的例子：
> > > > `d = <font color=red>`opening a gap`</font> ; e = <font color=red>`extending a gap`</font>`
> > > > 公式的例子：
> > > > `$$ F(i,y) = max\begin{cases} F(i-1,j+1) + s(x_i,y_j) \\\\ F(i-1,j)+d \\\\ F(i,j-1)+d \end{cases} $$`
> > > 
> > > 
> > > 关于字变红，你可以在管理后台自定义的地方加一个 ，我这边是不会改整体样式的哟。
> > > ![image](https://user-images.githubusercontent.com/23736683/89161176-d732b980-d5a4-11ea-8891-16f16224d43d.png)
> > > ```css
> > > <style type="text/css">
> > > code {    color: inherit !important;}
> > > </style>
> > > ```
> > 
> > 
> > 好的~感谢大佬 我去添加尝试一下，另外大佬我可以把typora的vue主题的css文件如何改改应用到主题上吗？发给您一个vue的css文件，另外公式那个我查了查也不知道怎么解决😭 感谢！
> > [vue.css.zip](https://github.com/hshanx/halo-theme-xue/files/5014715/vue.css.zip)
> 
> 这个vue主题，如果要完整引入的话，需要引入字体，对已这个来说，就有点大了。如果你要弄，我可以给你说怎么自定义，但是我计划作为主题的新功能了

新功能就真的太棒啦！ 那就先暂时这样用着吧，期待大佬更新这个新功能哈哈，可以加大佬一个联系方式吗？我感觉我平时问题挺多哈哈😜

**Comment by hshanx** [comment]
> > > > > > > > > https://www.haoxi.info/archives/typora%E5%92%8Cblogmd
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 这个不是bug哟，你写的样式作用在了 `font` 标签上面。并且 `code` 是有一个默认颜色的
> > > > > > > > ![image](https://user-images.githubusercontent.com/23736683/89145371-1e0fb780-d583-11ea-9e89-8f61e062affc.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 请教大佬那我要实现高亮字变红那要怎么在markdown中实现呀，还有公式那个提问中有一个mardown写的公式，大佬可以看一下~感谢😝
> > > > > > 
> > > > > > 
> > > > > > 你来个文本呀，图片的都复制不了
> > > > > 
> > > > > 
> > > > > 好嘞~😬
> > > > > 字变红的例子：
> > > > > `d = <font color=red>`opening a gap`</font> ; e = <font color=red>`extending a gap`</font>`
> > > > > 公式的例子：
> > > > > `$$ F(i,y) = max\begin{cases} F(i-1,j+1) + s(x_i,y_j) \\\\ F(i-1,j)+d \\\\ F(i,j-1)+d \end{cases} $$`
> > > > 
> > > > 
> > > > 关于字变红，你可以在管理后台自定义的地方加一个 ，我这边是不会改整体样式的哟。
> > > > ![image](https://user-images.githubusercontent.com/23736683/89161176-d732b980-d5a4-11ea-8891-16f16224d43d.png)
> > > > ```css
> > > > <style type="text/css">
> > > > code {    color: inherit !important;}
> > > > </style>
> > > > ```
> > > 
> > > 
> > > 好的~感谢大佬 我去添加尝试一下，另外大佬我可以把typora的vue主题的css文件如何改改应用到主题上吗？发给您一个vue的css文件，另外公式那个我查了查也不知道怎么解决😭 感谢！
> > > [vue.css.zip](https://github.com/hshanx/halo-theme-xue/files/5014715/vue.css.zip)
> > 
> > 
> > 这个vue主题，如果要完整引入的话，需要引入字体，对已这个来说，就有点大了。如果你要弄，我可以给你说怎么自定义，但是我计划作为主题的新功能了
> 
> 刚才看错啦哈哈，以为大佬要作为新功能，可以加大佬一个联系方式吗？我感觉我平时问题挺多哈哈😜

可以给我发邮件：c@baozi.fun
