### ISSUE TITLE
附件不可以分页

### ISSUE THREAD

**Issue by javami888** [xzzai/halo-theme-xue#25]
https://championmi.cn/upload/2020/08/chrome-capture-a033a87b4f0449f5a4d0ec6a6bb97566.gif

选择图片时候不能 翻页

**Comment by hshanx** [comment]
你这是后台还是主题？

**Comment by javami888** [comment]
后台



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hshanx"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 晚上9:35
收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25)





 
你这是后台还是主题？

**Comment by hshanx** [comment]
> 后台
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧

**Comment by javami888** [comment]
好的&nbsp; 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hshanx"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 上午8:57
收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25)





  
后台
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧

**Comment by javami888** [comment]
大佬问题解决了&nbsp; ，是加了CDN后没有配置参数跟随， 但是新的问题是&nbsp; 我的文章界面https://gitee.com/championmi/gitee_graph_bed/raw/master/img/20200806124609.png
赞助按钮&nbsp; 需要刷新一次 才可以点出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hshanx"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 上午8:57
收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25)





  
后台
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧

**Comment by xzzai** [comment]
> 大佬问题解决了&nbsp; ，是加了CDN后没有配置参数跟随， 但是新的问题是&nbsp; 我的文章界面https://gitee.com/championmi/gitee_graph_bed/raw/master/img/20200806124609.png 赞助按钮&nbsp; 需要刷新一次 才可以点出来
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 上午8:57 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 后台 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

等晚上回去看看

**Comment by javami888** [comment]
好的 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "宅家小能手"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 下午4:45
收件人: "xzzai/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xzzai/halo-theme-xue] 附件不可以分页 (#25)





  
大佬问题解决了&nbsp; ，是加了CDN后没有配置参数跟随， 但是新的问题是&nbsp; 我的文章界面https://gitee.com/championmi/gitee_graph_bed/raw/master/img/20200806124609.png 赞助按钮&nbsp; 需要刷新一次 才可以点出来
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 上午8:57 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 后台 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
等晚上回去看看

**Comment by xzzai** [comment]
> 好的 谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "宅家小能手"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 下午4:45 收件人: "xzzai/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [xzzai/halo-theme-xue] 附件不可以分页 (#25) 大佬问题解决了&nbsp; ，是加了CDN后没有配置参数跟随， 但是新的问题是&nbsp; 我的文章界面https://gitee.com/championmi/gitee_graph_bed/raw/master/img/20200806124609.png 赞助按钮&nbsp; 需要刷新一次 才可以点出来 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 上午8:57 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 后台 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 等晚上回去看看 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你还是把你的网址发我看下吧

**Comment by javami888** [comment]
championmi.cn






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "宅家小能手"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 下午4:48
收件人: "xzzai/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xzzai/halo-theme-xue] 附件不可以分页 (#25)





  
好的 谢谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "宅家小能手"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 下午4:45 收件人: "xzzai/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [xzzai/halo-theme-xue] 附件不可以分页 (#25) 大佬问题解决了&nbsp; ，是加了CDN后没有配置参数跟随， 但是新的问题是&nbsp; 我的文章界面https://gitee.com/championmi/gitee_graph_bed/raw/master/img/20200806124609.png 赞助按钮&nbsp; 需要刷新一次 才可以点出来 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月6日(星期四) 上午8:57 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 后台 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hshanx"<notifications@github.com&gt;; 发送时间: 2020年8月4日(星期二) 晚上9:35 收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hshanx/halo-theme-xue] 附件不可以分页 (#25) 你这是后台还是主题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 后台的话，我就真的没有办法了。你给 halo-dev/halo-admin 这个仓库提一个issues吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 等晚上回去看看 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你还是把你的网址发我看下吧

**Comment by xzzai** [comment]
> championmi.cn

可以呀，我点是好的。你清一下你本地的缓存吧

**Comment by javami888** [comment]
好 麻烦大哥了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "宅家小能手"<notifications@github.com&gt;; 
发送时间: 2020年8月6日(星期四) 下午4:51
收件人: "xzzai/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xzzai/halo-theme-xue] 附件不可以分页 (#25)





  
championmi.cn
  
可以呀，我点是好的。你清一下你本地的缓存吧
