### ISSUE TITLE
console里打印的这个github地址感觉不怎么合适

### ISSUE THREAD

**Issue by sheiy** [xzzai/halo-theme-xue#31]
![image](https://user-images.githubusercontent.com/12210038/89664257-763f1480-d909-11ea-84a6-083adb13f3ee.png)
建议要么打印用户设置的要么不打印毕竟博客属于比较个性化的网站

**Comment by xzzai** [comment]
现在应该不是这样子吧，现在是根据自己定义github 地址。

**Comment by sheiy** [comment]
嗯 现在好了 感谢大佬
