### ISSUE TITLE
搜索页面 BUG

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#32]
搜索页面没有下一页，搜索页面默认只展示了 5 条数据，实际数据多余五条，建议增加下拉 ajax，下拉时自动加载下一页

**Comment by xzzai** [comment]
这个应该不是一个bug，目前是默认显示所有的搜索结果

**Comment by zhixiangyuan** [comment]
> 这个应该不是一个 bug，目前是默认显示所有的搜索结果

大佬，我博客上带 java 关键字的博客是超过 100 篇的，这里应该是少了加载下一页的按钮

**Comment by xzzai** [comment]
恩，可以后面加上分页按钮

**Comment by xzzai** [comment]
最新版本已修复
