### ISSUE TITLE
目录过长被省略

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#33]
目录过长被省略，建议增加横向滑动的功能

![image](https://user-images.githubusercontent.com/25138766/89723981-ef388c00-da2f-11ea-91f3-8562e9411dc6.png)

**Comment by xzzai** [comment]
目录超过限制肯定会被隐藏的，不然会影响整个页面样式

**Comment by zhixiangyuan** [comment]
> 目录超过限制肯定会被隐藏的，不然会影响整个页面样式

这里是不是可以增加左右滚动框，如果想看完整目录可以向右拖动即可，这样直接省略掉的话就会出现看不到完整的目录

**Comment by xzzai** [comment]
> > 目录超过限制肯定会被隐藏的，不然会影响整个页面样式
> 
> 这里是不是可以增加左右滚动框，如果想看完整目录可以向右拖动即可，这样直接省略掉的话就会出现看不到完整的目录

并不会这么考虑，这样反而体验不好，为了这么点小优化牺牲整体的样式，有些得不偿失。并且有没有考虑过，为什么标题会这么长，感觉标题不应该这么长

**Comment by zhixiangyuan** [comment]
> > > 目录超过限制肯定会被隐藏的，不然会影响整个页面样式
> > 
> > 
> > 这里是不是可以增加左右滚动框，如果想看完整目录可以向右拖动即可，这样直接省略掉的话就会出现看不到完整的目录
> 
> 并不会这么考虑，这样反而体验不好，为了这么点小优化牺牲整体的样式，有些得不偿失。并且有没有考虑过，为什么标题会这么长，感觉标题不应该这么长

spring 里面有些类名字就很长，我直接用类名做标题就出现了这个问题😂

**Comment by xzzai** [comment]
> > > > 目录超过限制肯定会被隐藏的，不然会影响整个页面样式
> > > 
> > > 
> > > 这里是不是可以增加左右滚动框，如果想看完整目录可以向右拖动即可，这样直接省略掉的话就会出现看不到完整的目录
> > 
> > 
> > 并不会这么考虑，这样反而体验不好，为了这么点小优化牺牲整体的样式，有些得不偿失。并且有没有考虑过，为什么标题会这么长，感觉标题不应该这么长
> 
> spring 里面有些类名字就很长，我直接用类名做标题就出现了这个问题😂

可以参考一下掘金的目录处理，超过限制肯定是要隐藏。
![](https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/hsAmhN.png)

**Comment by zhixiangyuan** [comment]
> > > > > 目录超过限制肯定会被隐藏的，不然会影响整个页面样式
> > > > 
> > > > 
> > > > 这里是不是可以增加左右滚动框，如果想看完整目录可以向右拖动即可，这样直接省略掉的话就会出现看不到完整的目录
> > > 
> > > 
> > > 并不会这么考虑，这样反而体验不好，为了这么点小优化牺牲整体的样式，有些得不偿失。并且有没有考虑过，为什么标题会这么长，感觉标题不应该这么长
> > 
> > 
> > spring 里面有些类名字就很长，我直接用类名做标题就出现了这个问题😂
> 
> 可以参考一下掘金的目录处理，超过限制肯定是要隐藏。
> ![](https://camo.githubusercontent.com/a3822d8ce6140b3ff29c17c24fe2dd2c2cc602e7/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f787a7a61692f737461746963406d61737465722f755069632f6873416d684e2e706e67)

也挺好，看目录前面也够了
