### ISSUE TITLE
代码展示增强

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#34]
1. 建议增加这种代码展示风格，也很简洁大方

![image](https://user-images.githubusercontent.com/25138766/89713175-b1ece380-d9c8-11ea-83db-c3e5f9d718f4.png)

2. 代码高亮风格建议增加 AndroidStudio 风格，上图就是这个风格的代码展示，经常用 idea 的同学应该很熟悉这个配色

以上方案来自 https://github.com/LIlGG/halo-theme-sakura 这个主题，大佬可以考虑体验一下看一下效果

**Comment by xzzai** [comment]
现在已经够简洁了😂，只是说没有复制按钮，这个最开始也想做，但是没有实现。
其实说真的，我并不喜欢这左上角的按钮。
关于这种风格，算是一种Dark Theme。后面可能加上这种代码风格背景，且可以在白天模式使用这种风格。
代码高亮风格，可以后面也可以考虑新增。

**Comment by QianXun0827** [comment]
> 现在已经够简洁了😂，只是说没有复制按钮，这个最开始也想做，但是没有实现。
> 其实说真的，我并不喜欢这左上角的按钮。
> 关于这种风格，算是一种Dark Theme。后面可能加上这种代码风格背景，且可以在白天模式使用这种风格。
> 代码高亮风格，可以后面也可以考虑新增，因为现在也有很多种代码风格。

复制功能希望大佬可以加上，每次复制代码需要手动去选代码也挺麻烦的

**Comment by xzzai** [comment]
> > 现在已经够简洁了😂，只是说没有复制按钮，这个最开始也想做，但是没有实现。
> > 其实说真的，我并不喜欢这左上角的按钮。
> > 关于这种风格，算是一种Dark Theme。后面可能加上这种代码风格背景，且可以在白天模式使用这种风格。
> > 代码高亮风格，可以后面也可以考虑新增，因为现在也有很多种代码风格。
> 
> 复制功能希望大佬可以加上，每次复制代码需要手动去选代码也挺麻烦的

目前还没有找到一种好的方案
