### ISSUE TITLE
打开站点运行时间统计后出现的 bug

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#36]
我的博客：http://xiangbei.life/ ，chrome 打开页面即可复现 bug，一跳一跳的

![image](https://user-images.githubusercontent.com/25138766/89713808-bf0bd180-d9cc-11ea-9f24-677a1dd2daf7.png)
![image](https://user-images.githubusercontent.com/25138766/89713816-c59a4900-d9cc-11ea-90d4-f7eeaf5feddf.png)

**Comment by xzzai** [comment]
不清楚你是指的整个页面，还是值得这个运行时间，如果只是运行时间的话，运行时间是精确到秒的，每秒都会变的。

**Comment by zhixiangyuan** [comment]
> 不清楚你是指的整个页面，还是值得这个运行时间，如果只是运行时间的话，运行时间是精确到秒的，每秒都会变的。

是这个时间比如说 `749` 和 `天` 之间间距会变化，大佬用 chrome 打开我的博客拉到最下面就能看到这个 bug，safari 打开则没有这个问题

![image](https://user-images.githubusercontent.com/25138766/89726772-df7d6f80-da50-11ea-81d2-9502d9912003.png)

**Comment by xzzai** [comment]
我用自己的电脑看了下。
这是Chrome下面
![image](https://user-images.githubusercontent.com/23736683/89862207-06b37880-dbda-11ea-924c-c428c7737088.png)
这是Safari下面：
![image](https://user-images.githubusercontent.com/23736683/89862216-0dda8680-dbda-11ea-94d3-729ad1c7e84f.png)
并没有发现你说的问题

**Comment by zhixiangyuan** [comment]
这是我这边看到的结果

![image](https://user-images.githubusercontent.com/25138766/90162522-56a36280-ddc7-11ea-96b2-512960865430.png)

**Comment by xzzai** [comment]
应该是每秒都在跳。我改成静态的吧，每次刷新这里才会变化
