### ISSUE TITLE
卡片随机封面失效

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#37]
提示操作的 https://baozi.fun/archives/random-thumbnail 这个页面也 404 了

![image](https://user-images.githubusercontent.com/25138766/89713869-2d509400-d9cd-11ea-9d9c-351b1f8c1980.png)

**Comment by xzzai** [comment]
https://baozi.fun/2020/06/03/random-thumbnail
可以参考这篇文章，下个版本修复一下。
