### ISSUE TITLE
大佬，首页默认只能展示 5 篇博客怎么调

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#38]
大佬首页默认只能展示 5 篇博客怎么调，怎么调整首页博客数量，我在设置里面没找到

**Comment by xzzai** [comment]
后台可以调的.
![](https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/R2BYFH.png)

**Comment by zhixiangyuan** [comment]
> 后台可以调的.
> ![](https://camo.githubusercontent.com/48de9f66c7d64f653e1129c4c6b48243d16537ae/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f787a7a61692f737461746963406d61737465722f755069632f5232425946482e706e67)

棒
