### ISSUE TITLE
随机图片增强

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#39]
1. 这里随机图片的时候需要选择后缀，实际使用的时候可能会有各种图片类型，是否可以增加选项支持三种图片后缀
2. 随机图片数量可以默认为 thumbnail 目录下的图片数量
3. 目前如果选择的是 jpg，而图片后缀为 JPG 也显示不出来，可以考虑兼容大小写模糊处理

![image](https://user-images.githubusercontent.com/25138766/89727215-266d6400-da55-11ea-91e1-7a3b0a4dc1d2.png)

**Comment by xzzai** [comment]
1. 关于图片格式，我觉得这三个应该可以满足大部分的场景，多了反倒是复杂了。
2. 做的时候是有想法做成thumbnail目录下图片的数量的，但是我获取不到啊。
3. 这个可以上传图片的时候注意下，这个目前的技术好像是实现不了。
随机图片其实本来就是一个很鸡肋的功能，从halo官方到主题都不能很好支持。

**Comment by zhixiangyuan** [comment]
> 1. 关于图片格式，我觉得这三个应该可以满足大部分的场景，多了反倒是复杂了。
> 2. 做的时候是有想法做成 thumbnail 目录下图片的数量的，但是我获取不到啊。
> 3. 这个可以上传图片的时候注意下，这个目前的技术好像是实现不了。
>    随机图片其实本来就是一个很鸡肋的功能，从 halo 官方到主题都不能很好支持。

这块我的理解没必要区分文件类型，直接拿文件展示就好了
