### ISSUE TITLE
目录增强

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#40]
1. 当侧边栏直接出现目录的时候建议添加自动展开二级目录的功能
2. 二级目录目前没有缩进，看起来不明显

![image](https://user-images.githubusercontent.com/25138766/89728177-cf1fc180-da5d-11ea-9a0b-328896b2a9d2.png)

**Comment by xzzai** [comment]
原点是变小的

**Comment by zhixiangyuan** [comment]
> 原点是变小的

1. 这种形式的目录没有缩进看起来很不直观
2. 能不能后台加一个配置支持自动展开目录

**Comment by zhixiangyuan** [comment]
> 原点是变小的

目录能够增加一个配置，默认展示这种样式的目录

![image](https://user-images.githubusercontent.com/25138766/90315926-df4e0a00-df51-11ea-9bbb-1e3875d13adc.png)

**Comment by xzzai** [comment]
> > 原点是变小的
> 
> 目录能够增加一个配置，默认展示这种样式的目录
> 
> ![image](https://user-images.githubusercontent.com/25138766/90315926-df4e0a00-df51-11ea-9bbb-1e3875d13adc.png)

没懂，你是要展示成什么样式呢？
