### ISSUE TITLE
友链未按排序显示

### ISSUE THREAD

**Issue by sheiy** [xzzai/halo-theme-xue#41]

**Comment by QianXun0827** [comment]
友链显示排序按的是倒序显示，标号大的排在前面，希望能改为从小到大排序。

**Comment by xzzai** [comment]
> 友链显示排序按的是倒序显示，标号大的排在前面，希望能改为从小到大排序。

本来就是标号大的排在前面

**Comment by xzzai** [comment]
标号越大，说明权重越大，理应排在前面
