### ISSUE TITLE
归档页分页问题

### ISSUE THREAD

**Issue by zhixiangyuan** [xzzai/halo-theme-xue#43]
最新版将归档页改为了分页，这里能不能加个配置项，让用户选择归档页是否分页，搜索页同理。

**Comment by xzzai** [comment]
我考虑下怎么做，不是很好做

**Comment by zhixiangyuan** [comment]
> 我考虑下怎么做，不是很好做

大佬辛苦了

**Comment by xzzai** [comment]
突然发现后台可以设置归档页分页条数，如果归档页不考虑分页，这个地方可以设置大一些
![image](https://user-images.githubusercontent.com/23736683/95456968-c0448500-09a2-11eb-9408-df51d1a75e8a.png)

**Comment by xzzai** [comment]
搜索页面不能做成飞不分页的
