### ISSUE TITLE
markdown 表格渲染问题

### ISSUE THREAD

**Issue by 1205747671** [xzzai/halo-theme-xue#47]
在halo后台中的markdown编辑器：
```
表格：
|表头|第二列|第三列|
|-|-|-|
|第二行|第二列|第三列|
|第三行|第二列|第三列|

对齐表格：
|该列左对齐|第二列|该列右对齐|
|:-|:-:|-:|
|第二行|第二列|第三列|
|第三行|第二列|第三列|
```

在halo预览中的效果：
![image](https://user-images.githubusercontent.com/38599758/91625677-e3f7d100-e9db-11ea-8270-c259f544c3f1.png)

在雪主题的博客中的效果:
![image](https://user-images.githubusercontent.com/38599758/91625699-19042380-e9dc-11ea-8aa4-02b0fd88c3fc.png)

**Comment by xzzai** [comment]
来个示例地址呢

**Comment by xzzai** [comment]
下个版本修复掉，但是下面内容中的 对齐表格： 需要换行

对齐表格：
|该列左对齐|第二列|该列右对齐|
|:-|:-:|-:|
|第二行|第二列|第三列|
|第三行|第二列|第三列|

**Comment by xzzai** [comment]
请关注最新版本
