### ISSUE TITLE
任务列表渲染问题

### ISSUE THREAD

**Issue by codeyee** [xzzai/halo-theme-xue#48]
### 问题描述

使用markdown语法 `-  [  ]`  编写任务列表，但在该主题中实际渲染成了无序列表

###  halo编辑器中渲染的效果

![image](https://user-images.githubusercontent.com/43313765/91651322-0104d080-eabe-11ea-8c88-32ca939af9d2.png)

### Xue主题实际渲染的效果

![image](https://user-images.githubusercontent.com/43313765/91651334-17ab2780-eabe-11ea-86fa-9b34af84437a.png)

### 预期结果

在文章页面正常的渲染出任务列表

**Comment by xzzai** [comment]
看了下是正常的哟
![image](https://user-images.githubusercontent.com/23736683/94502808-8ef7e680-0237-11eb-8077-d223e463c0c6.png)

![image](https://user-images.githubusercontent.com/23736683/94502823-97502180-0237-11eb-8689-660f5ca0ae5c.png)

**Comment by xzzai** [comment]
但是也有可能是我使用的halo最新版本，因为这个本来就是后端渲染的

**Comment by xzzai** [comment]
请关注最新版本
