### ISSUE TITLE
建议增加自动开启夜间模式功能

### ISSUE THREAD

**Issue by zwc456baby** [xzzai/halo-theme-xue#49]
这个主题功能非常完善，而且更新频率也很高。

十分感谢

目前看到夜间模式
建议在主题设置内增加自动开启夜间模式选项

例如定时开启：晚上七点到 第二天 6点自动开启夜间模式

或者自动开启：跟随系统的夜间模式设定，Saferi 或者 Chrome 浏览器目前是有属性的

可以使用 js 调用，获取得知手机用户当前是否处于夜间模式下

---

![微信截图_20200907114942](https://user-images.githubusercontent.com/20961202/92346759-5d8c6f00-f100-11ea-8869-300d4904e58d.png)

---

很抱歉我并非web开发，无法验证这种 js 代码获取的方式是否可行，仅供参考

**Comment by xzzai** [comment]
可以，后期可以看看，这个功能还是很好的。
之前有根据时间来自动设置夜间模式，但是这个功能当时有点小缺陷，不是特别好，所以后面直接改成手动控制了

**Comment by zwc456baby** [comment]
自己动手，丰衣足食

修改 `source/js/_plugins/night-mode.js` 文件记录：

修改后经过测试是可以的~~~ 而且不影响手动开关夜间模式的功能。

```
// 首先定义一个key：
var userSelectNightModeId = 'userSelectNightMode';
 
// 在 clickNightMode 方法中增加一行，原有的不要动
//这里的目的是记录用户已经手动选择过夜间模式了
//如果用户点击 switch，手动开关了夜间模式，就不要自动跟随系统的夜间模式了
hanUtils.setLocalStorage(userSelectNightModeId, true);
 
    autoNightMode: function () {
        // 如果用户手动选择过夜间模式,则不要自动跟随系统的夜间模式，而是继续用之前的模式
        // 如果用户未手动选择过，则自动跟随系统的夜间模式
        if(hanUtils.getLocalStorage(userSelectNightModeId)){
            // 根据当前时间判断是否是晚上
            // 如果当前是晚上,由于各种设置会不一样,这里干脆写死, 并且开启了自动夜晚模式
            nightMode.changeNightMode(hanUtils.getLocalStorage(nightModeId));
        }else{
            nightMode.changeNightMode(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches);
        }
    }
```
