### ISSUE TITLE
请教journals页面的数据从哪里来？

### ISSUE THREAD

**Issue by kevin-hans** [xzzai/halo-theme-xue#50]
我菜单里已经添加了/journals，不过没有数据，空页面。
请问数据从哪里来？

`${journal.xxx!}`

**Comment by xzzai** [comment]
就是管理后台的日志数据
![image](https://user-images.githubusercontent.com/23736683/92424910-3d1feb80-f1b8-11ea-85f1-9266c1f70bd4.png)

![image](https://user-images.githubusercontent.com/23736683/92424928-49a44400-f1b8-11ea-8639-88204bb7d023.png)

**Comment by kevin-hans** [comment]
多谢！
