### ISSUE TITLE
左下角aplayer能不能默认关闭歌词显示功能

### ISSUE THREAD

**Issue by coppea** [xzzai/halo-theme-xue#51]
<img width="1425" alt="截屏2020-09-12 19 42 34" src="https://user-images.githubusercontent.com/34027147/92994832-63cf8080-f530-11ea-8db9-e9ba87e85d52.png">

确实影响美观

**Comment by xzzai** [comment]
我目前还没有找到，你可以看看这个仓库
https://github.com/metowolf/MetingJS

**Comment by coppea** [comment]
看样子好像要自建api
