### ISSUE TITLE
文章页头像丢失

### ISSUE THREAD

**Issue by 129duckflew** [xzzai/halo-theme-xue#53]
![image](https://user-images.githubusercontent.com/62204325/93368902-2e54cb00-f881-11ea-80f8-3934103618ca.png)
文章页面这个头像是在后台设置的吗？  我设置的在其他主题是正常的
站点:duckflew.cn

**Comment by xzzai** [comment]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/23736683/93430257-fc7d4c00-f8f4-11ea-9586-4f7ce04b5cbe.png">

看起来是好的

**Comment by 129duckflew** [comment]
> <img alt="image" width="1429" src="https://user-images.githubusercontent.com/23736683/93430257-fc7d4c00-f8f4-11ea-9586-4f7ce04b5cbe.png">
> 
> 看起来是好的

已经解决  谢谢！  出现问题的原因是我的个人资料的头像上传的格式为jpg  转换 成PNG恢复正常
