### ISSUE TITLE
日志页面渲染问题

### ISSUE THREAD

**Issue by xiaofsu** [xzzai/halo-theme-xue#54]
![image](https://user-images.githubusercontent.com/46067472/93560136-05812280-f9b4-11ea-8c2d-97431b0aba68.png)

日志页面貌似展示有些问题，而且元素是不是有点小？https://baozi.fun/journals

**Comment by xiaofsu** [comment]
![image](https://user-images.githubusercontent.com/46067472/93564610-8d6b2a80-f9bc-11ea-909f-a2cfa299f01f.png)

归档中只展示10条数据

**Comment by xzzai** [comment]
日子页面目前有点问题，正在修复中
