### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by zze326** [xzzai/halo-theme-xue#55]
除首页之外的列表分页都是10条数据每页，后台设置的分页值不起作用

**Comment by zze326** [comment]
比如标签的分页列表、分类的分页列表

**Comment by xzzai** [comment]
确实可能有这个问题，这个应该是后台代码写死了。我再下去研究下

**Comment by xzzai** [comment]
> 比如标签的分页列表、分类的分页列表
这个的分页条数是通过下面的配置来控制的
![image](https://user-images.githubusercontent.com/23736683/95459063-ab1d2580-09a5-11eb-8644-fda30a134bf1.png)

**Comment by xzzai** [comment]
https://github.com/halo-dev/halo/issues/1101
