### ISSUE TITLE
代码块assembly代码过长时未出现横向滚动条，直接跑到外头了

### ISSUE THREAD

**Issue by kn0sky** [xzzai/halo-theme-xue#56]
代码块assembly代码过长时无法自动换行，直接跑到外头了，如下图：
![image](https://user-images.githubusercontent.com/48575918/93864860-13a6aa00-fcf8-11ea-96a7-0002b4a3076b.png)

**Comment by xzzai** [comment]
正在修改这个问题，下个版本修复掉

**Comment by xzzai** [comment]
请关注最新版本
