### ISSUE TITLE
图片加载进度

### ISSUE THREAD

**Issue by xiaofsu** [xzzai/halo-theme-xue#6]
![image](https://user-images.githubusercontent.com/46067472/87907001-4e8d2700-ca96-11ea-8ae7-8964a4c32900.png)

服务器宽带较小时，对于一次加载较多图片压力很大，能否来一个loading框加载图片，例如黑果小兵的loading加载框。

[黑果小兵](https://blog.daliansky.net/)
![image](https://user-images.githubusercontent.com/46067472/87907084-7c726b80-ca96-11ea-908a-c48f93ddd12d.png)

**Comment by xzzai** [comment]
除了这个有什么好的插件吗？

**Comment by xzzai** [comment]
请看 1.2.2 版本
