### ISSUE TITLE
在首页能随机的图片点开具体文章后没有首部图片

### ISSUE THREAD

**Issue by zznEo** [xzzai/halo-theme-xue#61]
使用的主题版本为1.19
在成功设置了卡片随机选择封面后，点开文章内，首部没有图片
![image](https://user-images.githubusercontent.com/52597584/94412957-059bd200-01ad-11eb-8a83-4435bf5d91e1.png)

![image](https://user-images.githubusercontent.com/52597584/94412785-cec5bc00-01ac-11eb-8cd8-c535f7e1dfa4.png)

![image](https://user-images.githubusercontent.com/52597584/94412979-0d5b7680-01ad-11eb-9d14-ce930307594d.png)

[点这里](https://neo00.top/)

**Comment by zznEo** [comment]
补充，随机图片的每一页都是同样的图片，都是静态存储里面的前几个

**Comment by xzzai** [comment]
文章页面暂时还不支持随机图片

**Comment by zznEo** [comment]
> 文章页面暂时还不支持随机图片

就是文章的首部图片还是需要单独上传嘛

**Comment by xzzai** [comment]
下个版本支持。

**Comment by xzzai** [comment]
请关注最新版本
