### ISSUE TITLE
期望大佬可以增加一言功能

### ISSUE THREAD

**Issue by But-Always** [xzzai/halo-theme-xue#65]
期望大佬可以增加一言功能，放置在博客标题下面就可以，
$.get("https://v1.hitokoto.cn", function(msg){$("#main .hero-text").eq(0).html(msg.hitokoto + " -- " + msg.from);});

我这样加上之后页面跳转就没有了，刷新页面才能出来，希望大佬可以集成一下

**Comment by xzzai** [comment]
这个呀，我在想是否可以通过配置的形式来展现。因为我也想在我的标题下面加一个今日诗词

**Comment by xzzai** [comment]
下个版本就支持了，根据id写上你的脚本就好了

**Comment by But-Always** [comment]
嗯嗯 好的 期待下个版本的更新。
这个文章的展示方式能可以像之前的halo-theme-hshan那样配置几种不同的展示方式吗？还有halo-theme-hshan这个主题的自定义功能也很好用，不知道方便加上吗？
只是提出自己的看法，如有冒犯还请包涵。

**Comment by xzzai** [comment]
请关注最新版本
