### ISSUE TITLE
主页显示问题

### ISSUE THREAD

**Issue by ssymon** [xzzai/halo-theme-xue#72]
![image](https://user-images.githubusercontent.com/37892706/94988897-2e540b00-05a3-11eb-9307-169c84ab8169.png)
![image](https://user-images.githubusercontent.com/37892706/94988917-49267f80-05a3-11eb-8fce-fbf75abe4f24.png)

**Comment by ssymon** [comment]
切换 暗黑 时 导航栏 背景色

qq图标

**Comment by xzzai** [comment]
已修复
