### ISSUE TITLE
markdown  渲染二级标题出错

### ISSUE THREAD

**Issue by coppea** [xzzai/halo-theme-xue#73]
<img width="846" alt="截屏2020-10-03 21 19 49" src="https://user-images.githubusercontent.com/34027147/94992680-44bb9000-05be-11eb-93c0-d9a27cce6ca1.png">
还是显示H2，H3 的问题。我看别的网站使用这个标题也存在这个问题，难道是Chrome的问题吗

**Comment by xzzai** [comment]
标题的英文大写了吗？

**Comment by coppea** [comment]
> 标题的英文大写了吗？

我看所有的网站都有这个问题。不管是一级标题还是二级标题还是三级标题，都多余显示H1 H2 H3
<img width="900" alt="截屏2020-10-04 21 27 59" src="https://user-images.githubusercontent.com/34027147/95016930-da235680-0688-11eb-82cc-7aa14ec5ef00.png">

**Comment by coppea** [comment]
难道我理解错了，默认就是这么显示！！

**Comment by xzzai** [comment]
你指的是前面的 H1 H2 H3 吗？这个是默认这么现实的？

**Comment by coppea** [comment]
是的，就是默认显示的是吧

**Comment by xzzai** [comment]
> 是的，就是默认显示的是吧

是的，默认显示的
