### ISSUE TITLE
请问现在数学公式要怎么写才能正常显示

### ISSUE THREAD

**Issue by Smith-Cruise** [xzzai/halo-theme-xue#74]
之前用的 hansan 主题，在官方 issue 指导下写的数学公式显示正常，现在换成这个版本，数学公式都无法正常显示了。

请问标准的写法是怎么样的（块状和行内的）。附上一个简单的数学公式。

```
$$
\sqrt{123}
$$
```

**Comment by xzzai** [comment]
不好意思，这个版本我还没有测试数学公式，如果有问题，我下个版本会修复。

**Comment by Smith-Cruise** [comment]
麻烦博主测试下哈

**Comment by xzzai** [comment]
请查看1.2.2版本的hotfix.zip

**Comment by Smith-Cruise** [comment]
还是有点问题，多行公式无法显示，且
$$

$$
的语法下，公式应该是居中，这里都靠左对齐了。
附上问题页面：https://www.inlighting.org/archives/amdahls-law-and-its-proof

**Comment by xzzai** [comment]
![image](https://user-images.githubusercontent.com/23736683/95594092-0ec65200-0a7d-11eb-8757-521de21642ca.png)

你这个 在typora中也无法显示呀

**Comment by xzzai** [comment]
你如果要居中显示，可以在后台配置css的地方加上
```css
.katex-display {
    display: block !important;
}

```
