### ISSUE TITLE
分类标签分页问题

### ISSUE THREAD

**Issue by superdevops-cn** [xzzai/halo-theme-xue#75]
最新版本 选中分类标签的时候访问路径是正确的 https://superdevops.cn/categories/springcloud   
本分类标签下有2页内容   当点击第2页时 请求的url 变成  https://superdevops.cn/page/2 不会携带分类标签  
正确应为  https://superdevops.cn/categories/springcloud/page/2

**Comment by xzzai** [comment]
请查看1.2.2版本的hotfix.zip

**Comment by superdevops-cn** [comment]
> 请查看1.2.2版本的hotfix.zip
感谢大佬 亲测可以了
