### ISSUE TITLE
主页博客运行时长显示问题

### ISSUE THREAD

**Issue by junlongzzz** [xzzai/halo-theme-xue#76]
![image](https://user-images.githubusercontent.com/13492743/95454735-5dc89600-095c-11eb-9e5b-a40f100ea111.png)
如图，自从更新到1.2.x版本之后就不显示了，后台时间格式也是正常按规则设置的

**Comment by xzzai** [comment]
请查看1.2.2版本的hotfix.zip

**Comment by junlongzzz** [comment]
> 请查看1.2.2版本的hotfix.zip

已解决，只是现在变成了静态显示的策略了是吧

**Comment by xzzai** [comment]
是的
