### ISSUE TITLE
markdown文件  标题  tag 时间等消息无法正确显示

### ISSUE THREAD

**Issue by superdevops-cn** [xzzai/halo-theme-xue#78]

**Comment by superdevops-cn** [comment]
title: xxxx
date: 2019-12-01 10:20:13
tags:

Spring Cloud
Config
typora-root-url: …
 
1.2.2 出现此问题  1.19无此问题  正常情况下 博客中不会出现上述的内容

**Comment by xzzai** [comment]
你是怎么写的呢？

**Comment by xzzai** [comment]
感觉你说的根本都没有这个功能
