### ISSUE TITLE
Halo 控制台创建的二级目录，在主题中不按照二级目录显示

### ISSUE THREAD

**Issue by QianXun0827** [xzzai/halo-theme-xue#9]
在 Halo 控制台创建的二级、三级、四级目录是按照层级结果数显示的。

但是采用 halo-theme-xue-1.0.8 来显示的时候，所有的层级都展示在了第一级。

希望下个版本将这个问题修复一下，谢谢~！

期望样式：
![image](https://user-images.githubusercontent.com/40862062/86454651-24c3c880-bd52-11ea-96bb-878a940467aa.png)

**Comment by sheiy** [comment]
1.1.0二三级菜单没有只有一级菜单

**Comment by hshanx** [comment]
目前还没有支持二级菜单，后期优化加上，这个确实不是怎么好

**Comment by QianXun0827** [comment]
更新了最新版，已经修复了，大佬辛苦了
